### ISSUE TITLE
Consider vendoring the vault code

### ISSUE THREAD

**Issue by viktomas** [incipher/shamir#2]
The vault code is no longer open source: https://news.ycombinator.com/item?id=37081306

Since this project has very permissive public domain license (thank you for making this for free @itsabdelrahman 🙏 ), you might consider vendoring the vault code from this commit: https://github.com/hashicorp/vault/tree/ba215dbc1259e125e9e6a2551f6c71f47855d2e2 (that's the last that still used Mozzila (MPL) license).

This is just a suggestion, nothing critical. Either way thank you for the great work 🙇

**Comment by itsabdelrahman** [comment]
Hey @viktomas, appreciate the heads-up - that is indeed concerning news. Will pin the dependency at hashicorp/vault@ba215db as you suggested 👌 

Thank you very much for the kind words 😃

**Comment by viktomas** [comment]
Great, thank you as well 👋
